### ISSUE TITLE
Cannot install hypertag version 0.6.2.7

### ISSUE THREAD

**Issue by hiteshsom** [SeanPedersen/HyperTag#65]
Hi,

I am trying to install and use hypertag==0.6.2.7 but it is giving me following error

```
ERROR: Could not find a version that satisfies the requirement torchvision<0.9.0,>=0.8.2 (from hypertag)
ERROR: No matching distribution found for torchvision<0.9.0,>=0.8.2
```

Full traceback error
```
(hypertag_env) PS C:\<some path>\Documents> pip install hypertag==0.6.2.7
Collecting hypertag==0.6.2.7
  Using cached hypertag-0.6.2.7-py3-none-any.whl (27 kB)
ERROR: Could not find a version that satisfies the requirement torchvision<0.9.0,>=0.8.2 (from hypertag)
ERROR: No matching distribution found for torchvision<0.9.0,>=0.8.2
```

I am using gcp windows instance. `hypertag_env` is just a virtual environment with following package
```
numpy==1.19.5
pandas==1.2.1
python-dateutil==2.8.1
pytz==2020.5
six==1.15.0
```

Thanks in advance for help.

**Comment by SeanPedersen** [comment]
This software is not tested / developed on windows. And I have no access to a windows machine right now. Try running it with the windows Ubuntu kernel added to Windows 10.

**Comment by SeanPedersen** [comment]
This software is not tested / developed on windows. And I have no access to a windows machine right now. Try running it with the windows Ubuntu kernel added to Windows 10.
